console.log("=========================");
console.log("||    COMP 3123 Lab 2  ||");
console.log("==========================");
console.log();
console.log(" -- Exercise 01 --");
require('./exercise01.js');
console.log();
console.log(" -- Exercise 02 --");
require('./exercise02.js');
console.log();
console.log(" -- Exercise 03 --");
require('./exercise03.js');
console.log();
console.log(" -- Exercise 04 --");
require('./exercise04.js');
console.log();
console.log(" -- Exercise 05 --");
require('./exercise05.js');
console.log();
console.log(" -- Exercise 06 --");
require('./exercise06.js');
console.log();
